version: '3.8'  # Define Docker Compose file version
services:
  backend:
    build: ./mern/backend/
    container_name: backend
    ports:
      - "5050:5050" 
    depends_on:
      - mongodb  
    networks:
      - mern-network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  

  
  frontend:
    build: ./mern/frontend/  
    container_name: frontend
    ports:
      - "5173:5173"  
    environment:
      REACT_APP_API_URL: http://backend:5050
    depends_on:
      - backend  
    networks:
      - mern-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  
    networks:
      - mern-network

# Define named volumes
volumes:
  mongo-data:
    driver: local

# Define network for inter-service communication
networks:
  mern-network:
    driver: bridge
